onlyBuiltDependencies:
  - ','
  - '-'
  - /
  - '@'
  - '@parcel/watcher'
  - '@swc/core'
  - a
  - b
  - c
  - d
  - e
  - esbuild
  - h
  - i
  - l
  - m
  - msw
  - n
  - o
  - p
  - puppeteer
  - r
  - s
  - sharp
  - t
  - u
  - unrs-resolver
  - v
  - vue-demi
  - w
